### ISSUE TITLE
uninitialized constant ActiveRecord::ConnectionAdapters::ClosedTransaction

### ISSUE THREAD

**Issue by ShogunPanda** [igrigorik/em-synchrony#189]
Hi. I just upgraded to em-synchrony 1.0.4.
Whenever I try to make any operation with ActiveRecord I get this error using ActiveRecord 4.2.0:

```
Failure/Error: Unable to find matching line from backtrace
   NameError:
     uninitialized constant ActiveRecord::ConnectionAdapters::ClosedTransaction
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/em-synchrony/activerecord.rb:92:in `reset_transaction'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:6:in `initialize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:24:in `initialize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:102:in `initialize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:163:in `initialize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:35:in `initialize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/active_record/connection_adapters/em_mysql2_adapter.rb:34:in `new'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/active_record/connection_adapters/em_mysql2_adapter.rb:34:in `em_mysql2_connection'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/em-synchrony/activerecord.rb:12:in `block in connection'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/em-synchrony/thread.rb:63:in `synchronize'
   # /Volumes/DATI/Users/Shogun/.rvm/gems/ruby-2.2.0/gems/em-synchrony-1.0.4/lib/em-synchrony/activerecord.rb:11:in `connection'
```

Can you please fix it? :)

**Comment by Ravenstine** [comment]
I would also like to see this issue solved.

**Comment by johnnaegle** [comment]
+1

**Comment by kkempin** [comment]
+1

**Comment by est** [comment]
+1 same error here.

**Comment by vkill** [comment]
+1

**Comment by pablocrivella** [comment]
+1

**Comment by genail** [comment]
+1

**Comment by markalanevans** [comment]
+1

**Comment by rudyboy** [comment]
+1...

**Comment by rudyboy** [comment]
+1
Rollback to 1.0.3 can solve this problem.
Hope this issue to be solved soon.

**Comment by vkill** [comment]
rollback activerecord to 4.1.9

**Comment by Aetherus** [comment]
+1
4.1.10 is okay too.
Eager to see this issue being fixed so that we can leverage rails 4.2's active job.

**Comment by coxoc** [comment]
Fixed with the following patch.(not tested in production environment)

```
module EM::Synchrony
  module ActiveRecord
    module Adapter
      def reset_transaction #:nodoc:
        @transaction_manager = ::ActiveRecord::ConnectionAdapters::TransactionManager.new(self)
      end

      delegate :open_transactions, :current_transaction, :begin_transaction, :commit_transaction, :rollback_transaction, to: :transaction_manager
    end
  end
end
```

**Comment by ShogunPanda** [comment]
Any update on this?

**Comment by dgutov** [comment]
Should be fixed now with https://github.com/igrigorik/em-synchrony/commit/6c88bbf3607b2af027a7825c03aeb0ee2bdc2cb3 (although no new release yet).

**Comment by ShogunPanda** [comment]
Ok, any ETA for the new release?

**Comment by igrigorik** [comment]
@dgutov @ShogunPanda we're overdue for a release; I can push one out. That said, I'd love to see if we can get https://github.com/igrigorik/em-synchrony/pull/190 in first.

**Comment by dgutov** [comment]
@igrigorik From what I understand of #190, it would require a major version bump. I think it would be better to push out a backward-compatible release first.

**Comment by igrigorik** [comment]
@dgutov sounds reasonable. Side topic: can you please ping me on ilya@igvita.com? :)

**Comment by dgutov** [comment]
The new version has been released.
