### ISSUE TITLE
Fail with gem listen

### ISSUE THREAD

**Issue by Fudoshiki** [igrigorik/em-synchrony#211]
gem listen + em-synchrony in `Gemfile.rb`

result
```
E, [2016-11-30T00:35:50.821989 #19799] ERROR -- : exception while processing events: wrong number of arguments (given 0, expected 1) Backtrace:
 -- ../.rvm/gems/ruby-2.3.3@Honshu/gems/em-synchrony-1.0.5/lib/em-synchrony/kernel.rb:13:in `sleep'
 -- ../.rvm/gems/ruby-2.3.3@Honshu/gems/listen-3.1.5/lib/listen/event/loop.rb:96:in `_wait_until_resumed'
 -- ../.rvm/gems/ruby-2.3.3@Honshu/gems/listen-3.1.5/lib/listen/event/loop.rb:83:in `_wait_for_changes'
 -- ../.rvm/gems/ruby-2.3.3@Honshu/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- ../.rvm/gems/ruby-2.3.3@Honshu/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by dgutov** [comment]
This is already fixed in master, but hasn't gotten into any release yet. Maybe now's the time.

@igrigorik Whenever it's convenient for you, please.

**Comment by igrigorik** [comment]
Done deal: https://github.com/igrigorik/em-synchrony/commit/f26d85fba39420b8615e835de727c84bf0adb357. :)
